version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:15.11.0
    working_directory: ~/ecommerce

    steps:
      - checkout
      - run: node --version
      - run: npm install
  build:
    docker:
      - image: cimg/node:15.11.0
    working_directory: ~/ecommerce
    steps:
      - run: echo "run build task"
      - run: npm run build
  deploy:
    docker:
      - image: cimg/node:15.11.0
    working_directory: ~/ecommerce
    steps:
      - checkout
      - run: echo "build project"
      - run: ssh -i -v ${VPS_USER}@${IP} "~/cmsrepo_deploy.sh"
workflows:
  version: 2
  test-build:
    jobs:
      - test
      - build:
          filters:
            branches:
              only:
                - master
