version: 2.1

jobs:
  build:
    docker:
      - image: arvind226/alpine-ssh
    steps:
      - checkout
      - run: 
          command: echo ${VPS_USER}
          ssh -oStictHostKeyChecking-no -v ${VPS_USER}@${IP} "./deploy.sh"
workflows:
  version: 2
  build-project:  
    jobs:
      - build
        filters:
          branches:
            only:
              - master  
