version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:15.11.0
    working_directory: ~/ecommerce
    steps:
      - checkout
      - run: node --version
      - run: npm install
  build:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run: echo "build project"
      - run: ssh -i -v ${VPS_USER}@${IP} "~/cmsrepo_deploy.sh"
workflows:
  version: 2
  build-project:
    jobs:
      - test
      - build:
          filters:
            branches:
              only:
                - master
