version: 2.1

jobs:
  build:
    machine:
      - image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run: ssh -oStictHostKeyChecking-no -v ${VPS_USER}@${IP} "./deploy.sh"
workflows:
  version: 2
  build-project:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
