version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:15.11.0
    working_directory: ~/ecommerce

    steps:
      - checkout
      - run: node --version
      - run: npm install
  build:
    docker:
      - image: cimg/node:15.11.0
    working_directory: ~/ecommerce
    steps:
      - run: echo "run build task"
      - checkout
      - run: npm install
      - run: npm run build
  deploy:
    machine:
      image: ubuntu-1604:202007-01
    working_directory: ~/ecommerce
    steps:
      - checkout
      - run: echo "deploy project"
      - run: ssh -i -v ${VPS_USER}@${IP} "~/cmsrepo_deploy.sh"
workflows:
  version: 2
  test-build:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
