version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run: ssh -i -o stricthostkeychecking=no -v ${VPS_USER}@${IP} "./deploy.sh"
workflows:
  version: 2
  build-project:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
